### ISSUE TITLE
Linear algebra operations

### ISSUE THREAD

**Issue by tgregov** [tgregov/Multiphysics#10]
Basic linear algebra operations should be handled easily, most particularly:
- storage of large matrices/vectors
- inversion of a block-diagonal matrix
- matrix-vector multiplication
using an external library, most probably Eigen

**Comment by ImperatorS79** [comment]
If we go for Eigen, I have already update the project in my fork. I will do the PR when we agree.

**Comment by tgregov** [comment]
It don't think there will be any argument coming from Joachim or me against Eigen, since we don't know its advantages/drawbacks compared to the other libraries, so I guess it should be OK for us. The only possible disagreement might come from the teachers, but if the code works & is efficient it shouldn't be a problem hopefully.
