### ISSUE TITLE
Handle boundary conditions

### ISSUE THREAD

**Issue by tgregov** [tgregov/Multiphysics#14]

**Comment by tgregov** [comment]
@ImperatorS79 When considering our geometry with d set to 0.5, I can see that the BC are not set for the elements (in displayMesh, we just have `BC:`). It probably comes from Mesh2D, can you have a look at it ?

**Comment by ImperatorS79** [comment]
I am on it. `IsBoundary `has to be modified.

**Comment by ImperatorS79** [comment]
Ok, we have to modify how we handle the BC's in Mesh2D. `getNodesForPhysicalGroup` get the nodes of the element belonging to the `PhysicalGroup`, but the 1D elements do not exist at this time !

**Comment by tgregov** [comment]
Oh 😞  Can we still rely on you to try to recode it ?

**Comment by ImperatorS79** [comment]
Yes, but I don't know how to to do it indeed, How can I check inside the code that a node is in a BC ? Despite defining the BC with an equation and check that the nodes coordinate of an edge belongs to it, I do not see how I can do differently.

**Comment by tgregov** [comment]
So what is actually linked to a BC ? The element ?

**Comment by ImperatorS79** [comment]
NVM, it can actually works ! :man_facepalming: It is just that the `getNodesForPhysicalGroup` send a list of nodes, not per edge. So I think if I just check that both the nodes tags of an edge are inside it it should work ^^.

**Comment by tgregov** [comment]
Hmmm ok ahahah if it works it's ok for me

**Comment by ImperatorS79** [comment]
OK, I checked by stopping the program if `bcName.size()` is zero, and the program goes to the end :ouf;.

Edit: @tgregov Pushed.

**Comment by tgregov** [comment]
Sadly is still explodes 😢

**Comment by ImperatorS79** [comment]
Ah I expected that it will not solve all our problems :grin:.

**Comment by tgregov** [comment]
@ImperatorS79 I have found a mistake in our code !!!!!!!! (I think) I will study it and keep you informed 😅

**Comment by tgregov** [comment]
So basically we typed gx[j] instead of gx[edge.offsetInElm[j]] (at four lines). Unfortunately, it does not give a good solution, but it is still better than before

**Comment by tgregov** [comment]
By trying the weak form with S instead of S.tranpose(), it seems to be constant (i.e. I compensates S*f)
... but it gives bad results for a problem initiated with BC

**Comment by ImperatorS79** [comment]
@tgregov I have something quite better in preparation, stay tuned !
