### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by ImperatorS79** [tgregov/Multiphysics#21]
The code clearly needs to be cleaned and refactored, especially the `readMesh `function and the `MeshParams `structure. Some ideas:

- "Split" `MeshParams `into substructure to avoid using `vector `of `vector `of `vector`...
- Check if they are unneeded operations in `readMesh`, or if it could be split.
- Use OOP (`class`, ...)

**Comment by tgregov** [comment]
Ok. Just for the classes, we can definitely use them if they can provide additional clarity in the code, but we shouldn't put artificially too much OOP, as we have talked before. And maybe we could delete the old `Mesh` structure, and rename `MeshParams` using a simpler name e.g. `Mesh` 😄
