### ISSUE TITLE
Computation of fluxes gx gy in the no BC case

### ISSUE THREAD

**Issue by tgregov** [tgregov/Multiphysics#26]
Probably a non-initialized vector or a problem for the index of a vector
File builFlux.cpp, around line 140:
```c
gx[j] = -(factor*fx[element.offsetInU + j] + fx[frontOffsetInU + frontJ])/2 - C*element.edges[s].normal.first*(u[element.offsetInU + j] - valueAtBC())/2;
gy[j] = -(factor*fy[element.offsetInU + j] + fy[frontOffsetInU + frontJ])/2 - C*element.edges[s].normal.second*(u[element.offsetInU + j] - u[frontOffsetInU + frontJ])/2;
```

**Comment by ImperatorS79** [comment]
This does not seem to be an uninitialised vector or vector size problem, since on my computer the value stay the same between each run.

**Comment by tgregov** [comment]
Weird ! But you still have the problem of random values appearing ?

**Comment by ImperatorS79** [comment]
No, as I said, the values seem stupid, but they are the same between different runs.

**Comment by tgregov** [comment]
We still need to find the issue then

**Comment by tgregov** [comment]
And maybe the issue does not come from there too

**Comment by tgregov** [comment]
Ok the determinant edge.determinant1D[0] gives weird results /!\

**Comment by ImperatorS79** [comment]
Yes of course.

**Comment by tgregov** [comment]
"Mais oui c'est clair !"

**Comment by tgregov** [comment]
We were stupid, in display mesh we can already see that mistake 😢

**Comment by ImperatorS79** [comment]
This maybe comes from how I cut the determinant1D (which is for one eleType (thanks gmsh...)) vector per element per edge.

**Comment by ImperatorS79** [comment]
@tgregov This is definitely that

**Comment by tgregov** [comment]
Yes I was looking there too. Btw, determinants1D.size() has a length 24, I don't know if it makes sense or not. Also, we (maybe) still have the problem 2D type -> 1D type

**Comment by ImperatorS79** [comment]
```c
std::vector<double> determinantElement1D(
                                            determinants1D.begin() + numNodes*nGP2D*i,
                                            determinants1D.begin() + numNodes*nGP2D*(1 + i));
```
factor 3 missing at line 369 in Mesh2D ?

**Comment by tgregov** [comment]
I think so, maybe we should also rename addEdge to addEdges, so that it is clear that we add all the edges (and not just one)

**Comment by ImperatorS79** [comment]
Normally addEdge only add one Edge.

**Comment by tgregov** [comment]
Oh, my bad. Yep, sorry

**Comment by ImperatorS79** [comment]
That line is in addEntity, when we separate the determinant1D vector for an element.
In addElement, it is then separated for an edge.

**Comment by tgregov** [comment]
With the *3, does it work ?

**Comment by ImperatorS79** [comment]
No, *3 does not work. There is definitely a problem in how the vector is cut. I bet a factor plus a parenthesis problem.

**Comment by ImperatorS79** [comment]
Ok, it works with Gauss1, so I bet a parenthesis problem.
@tgregov  Edit: 
- `displayMesh `does display only first GP in determinant
- It seems there is 2 GP in 1D and 3 in 2D when `intScheme` is "Gauss2"

**Comment by ImperatorS79** [comment]
@tgregov okay fixed it

**Comment by tgregov** [comment]
Ok can you add it in the PR so that I can accept it ? The "projection" 2D->1D is still annoying me >:(

**Comment by tgregov** [comment]
@ImperatorS79 Is it ok for you for the merge ?

**Comment by ImperatorS79** [comment]
Yes, but we still have to check for the results in timeInteg :/.

**Comment by tgregov** [comment]
Of course, but at least you have found one mistake 😄
